name: copaw
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.10.0
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  google_sign_in: ^7.2.0
  flutter_chat_ui: ^2.9.1
  table_calendar: ^3.1.2
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  skeletonizer: ^2.1.0+1
  google_fonts: ^6.3.2
  cloud_firestore: ^6.0.3
  image_picker: ^1.2.1
  firebase_storage: ^13.0.4
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
